### PR TITLE
Add recursive flag to inGroup & getGroups methods

### PR DESCRIPTION
**Pull request by tof06**
#192

### CODE REVIEW

**Comment by Xento** [comment]
You only implemented one level of recursion. 
What if you have more nested groups and what if you build a loop with your groups?

**Comment by stevebauman** [comment]
Thanks!

**Comment by tof06** [comment]
@Xento You're right about nested group... Forgot to add the parameters in `getGroups̀
```
foreach ($groups as $group) {
                $groups = array_merge($groups, $group->getGroups($fields, $recursive));
            }
```
As I said in the issue, it was a quick patch... :) There's room for improvement

**Comment by ChadSikorra** [comment]
Would this lead to an infinite loop in the case of two groups that are members of each other? Not that it's a good practice..but it's not unallowed.

**Pull request merged**
