### PR TITLE
PSR-2 and php 5.4 array syntax

### PR DESCRIPTION
**Pull request by strebl**
Initial commit which changes the array syntax and makes the code passing PSR-2.

### CODE REVIEW

**Comment by strebl** [comment]
Will solve #16 and #17 if I didn't miss something.

**Comment by stevebauman** [comment]
Ah perfect! Was going to comment about the collision. This is great work, thanks!

**Comment by strebl** [comment]
Yeah, you're working to fast! :smile:

**Comment by stevebauman** [comment]
Haha sorry about that! Trying to get this thing tested and released

**Comment by strebl** [comment]
Go for it! Really like your speed! This package is amazing.

Keep up your good work!

Will try to help you as good as I can!

**Pull request merged**
