### PR TITLE
Construction method should not auto connect to ldap server

### PR DESCRIPTION
**Pull request by freefcw**
When Connection Provider object create, the connection will connect to ldap server, this may cause app slow when ldap server no reachable.

And It against auto connect, so I move connection  connect to Provider connect method, will control by auto_connect

### CODE REVIEW

**Comment by stevebauman** [comment]
The `ldap_connect` method only constructs a connection, it does not actually contact your server.

http://php.net/manual/en/function.ldap-connect.php

**Comment by mvatansever** [comment]
Thanks @stevebauman , I didn't notice this since I was interested the LDAP on PHP :) I sent a doc to contribute to PHP's manual for being more distinguishable the behavior. I hope they can accept that.

**Comment by stevebauman** [comment]
@mvatansever I agree, it's strange since their examples show a new connection being created or `die()` when it can't "connect", which is giving the wrong impression to developers that it's actually connecting to your server:

```php
// LDAP variables
$ldaphost = "ldap.example.com";  // your ldap servers
$ldapport = 389;                 // your ldap server's port number

// Connecting to LDAP
$ldapconn = ldap_connect($ldaphost, $ldapport)
          or die("Could not connect to $ldaphost"); // <- This is a misleading error message
```

**Comment by freefcw** [comment]
@stevebauman  Thanks for the docs, I check the man file, it not connect.So I will check my app for more environment, It's confused situation.

Sorry for this pr.

**Comment by stevebauman** [comment]
@freefcw It's okay! I really appreciate all issues and PR's. This will help any developer in the future who is mixed up about this as well, so thank you :smile:

If you have any issues with Adldap2 just create one and I will assist you there.

**Comment by freefcw** [comment]
@stevebauman 

Hello. the ldap_connect function cause our server slow down appear again.

Ｉ use wireshirk monitor network traffic, then found this function will connect to the ldap server, when our vpn disconnected, this make our fpm take more time to wait connect failed.

My merge request will solve this problem, so please consider it again. 

Thanks a lot.

**Comment by freefcw** [comment]
Sorry, the document is all right. I review all code of php ldap extension and openldap,  it's will not connect to the server.

But why my app connect to the ldap server ?

Wireshark tell me the fact,so I use xdebug_print_call_stack print call chain in php code, finally I found the SessionGuard class, method user() will call retrieveById of provider,

In the DatabaseUserProvider class, retrieveById() method will fetch the ldap user use model, so here will connect to the server.

So, it's nothing about ldap_connect, just remove HasLdapUser from User model, will make this problem destroy..

Hmm....It make me mad for a long time, just share this experiment for others.

**Comment by mvatansever** [comment]
Good explains. Most time we don't know how to manage session or other things the frameworks/packages we use. Thank you for revealing this issue.

**Comment by freefcw** [comment]
@mvatansever 

I found documents had explained this.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/binding.md

The documents add in 2017, Feb. but I add the package in 2016, June.

Hmm...I should take care of features, if not vpn problem, I never notice this feature actual meaning

**Pull request closed without merging**
