### PR TITLE
Alt fix user change password

### PR DESCRIPTION
**Pull request by jspringe**
This refers to PR #174. This fix doesn't change the default behavior of the method and should be more friendly in general. Hopefully StyleCI doesn't puke on me again.

Pick one - close the other :)

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks!

**Comment by chriseskow** [comment]
(Cross-posted from #174)

What's the difference between changePassword($unused, $newPassword, true) and setPassword($newPassword) with this change? They seem to perform the same operation now, which I'm not sure is (semantically) correct. At least with Active Directory, a DELETE followed by an ADD is considered to be a password change, while a REPLACE is considered to be an administrative password reset. They have different permission requirements.

See also:

http://serverfault.com/questions/423345/changing-active-directory-password-over-ldap-using-passwd-ldappasswd-samba
https://msdn.microsoft.com/en-us/library/cc223248.aspx

**Comment by jspringe** [comment]
For whatever reason on my setups the password would not change when using the DELETE / ADD method. I have to use the REPLACE method. For this reason I left the original code intact and just added an additional argument. 

At the very least this will cover additional edge cases without breaking the current API.

**Comment by jspringe** [comment]
How about we meet in the middle: One of us creates a new PR that will change the variable from `$replaceNotRemove` to `$administrativeReset` and update the DOCBLOCK. This way we cover all cases and it's properly named.

**Comment by chriseskow** [comment]
I have no qualms with the naming, I'm just wondering if the change is necessary, since if `changePassword()` isn't working you could call `setPassword()` instead.

But that being said, since this change is backwards compatible it's fine as-is for me! :+1:

**Comment by jspringe** [comment]
Ugh - well this is why we need to start working on the docs..

**Pull request merged**
