### PR TITLE
Add SSHA password transform function

### PR DESCRIPTION
**Pull request by flartet**
One day or another, this will help to improve OpenLDAP compatibility.
Or I misunderstood something, which is possible, I'm a beginner with this package.

### CODE REVIEW

**Comment by ekvedaras** [comment]
I also need something like this. But more importantly the current code uses `Utilities::encodePassword()`. We need an option to switch this to this one, otherwise it converts the password to `UTF-16LE` and surrounds with `"` which breaks authentication for that user. Can this be improved? If you need help we can discuss or I can submit another PR with this approach finalised.

**Comment by flartet** [comment]
By checking the schema ?
In my opinion the behavior should be coded in the User model (in the traits), not in the Utilities class.
I did a 2nd method to change password because I'm on fresh code and I can call the proper method.
So, a test on the schema, or maybe by testing the existing attributes.

**Comment by ekvedaras** [comment]
Can we provide different strategies for encoding the password and then you can set whichever you want to use on user model or in config somewhere?

**Comment by stevebauman** [comment]
Merged #732

**Pull request closed without merging**
